def Finished(self):
    self.ui.plainTextEdit.appendPlainText('\n\n\nПроверка прокси завершена!')
    self.ui.Start.setEnabled(True)
    self.ui.spinBox_2.setEnabled(True)
    self.ui.comboBox.setEnabled(True)
    self.ui.Select_proxy_button.setEnabled(True)
    self.ui.Textline.setEnabled(True)
    self.ui.all_proxy.setEnabled(True)
    self.ui.Start.setText('Начать')
    self.ui.plainTextEdit.appendPlainText('\n\nРезультаты проверки сохранены в файлы valid.txt и invalid.txt')
